// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQC1obuQJUFJKeQMFC6b5WbmorlVGPDEY',
    appId: '1:1045154677922:web:57a341d0f99c32dd1bc3fb',
    messagingSenderId: '1045154677922',
    projectId: 'planex-4cc13',
    authDomain: 'planex-4cc13.firebaseapp.com',
    storageBucket: 'planex-4cc13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDirxsscanwagyhtfCd-N9s5lGQo1lPh0A',
    appId: '1:1045154677922:android:2fd518742f1cbf261bc3fb',
    messagingSenderId: '1045154677922',
    projectId: 'planex-4cc13',
    storageBucket: 'planex-4cc13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-oeIlq8AJt1gWvAMERj-z_KBUfBdxhg',
    appId: '1:1045154677922:ios:538eff61372df66b1bc3fb',
    messagingSenderId: '1045154677922',
    projectId: 'planex-4cc13',
    storageBucket: 'planex-4cc13.firebasestorage.app',
    iosClientId: '1045154677922-nq4l1d31cg0lu2ravoomn3j9c9aedgpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.planExApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-oeIlq8AJt1gWvAMERj-z_KBUfBdxhg',
    appId: '1:1045154677922:ios:538eff61372df66b1bc3fb',
    messagingSenderId: '1045154677922',
    projectId: 'planex-4cc13',
    storageBucket: 'planex-4cc13.firebasestorage.app',
    iosClientId: '1045154677922-nq4l1d31cg0lu2ravoomn3j9c9aedgpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.planExApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQC1obuQJUFJKeQMFC6b5WbmorlVGPDEY',
    appId: '1:1045154677922:web:b57f5b28408ac6f11bc3fb',
    messagingSenderId: '1045154677922',
    projectId: 'planex-4cc13',
    authDomain: 'planex-4cc13.firebaseapp.com',
    storageBucket: 'planex-4cc13.firebasestorage.app',
  );

}